version: '3.7'
services:
    # nfvprime_postgres:
    #     build: 
    #        context: ./Postgres
    #     ports:
    #        - "5433:5432"
    #     container_name: nfvprime_postgres
    nfvprime_api:
      build:
        context: "./NFVPrimeBack"
      image: nfvprime_api:latest
      init: true
      security_opt:
        - seccomp:unconfined
      privileged: true
      container_name: nfvprime_api
      ports:
          - "23620:5000"
      environment:
        - "PGHOST=nfvprime_postgres"
        - "PGUSER=postgres"
        - "PGDATABASE=public"
        - "PGPASSWORD=postgres"
        - "PGPORT=5432"
        - "PORT=8080"
        - "LOGDIR=./log"
        - "JWTSECRET=test"
    nfvprime_ui:
        user: node
        build:
          context: "./NFVPrimeFront"
        image: nfvprime_ui:latest
        init: true
        container_name: nfvprime_ui
        ports:
          - "23621:3000"
